package com.siliqon.cosmiccosmetics.enums;

public enum EffectType {
    SPLASH, ENDER, FLAME, CHARM, LOVE, BLOSSOM, ENCHANTED, TEARS, MUSICAL,
    RAINBOW, CLOUDY, BALLOONS,
    CAPE_CRIMSON, CAPE_AZURE, CAPE_EMERALD, CAPE_VIOLET, CAPE_RAINBOW, CAPE_GOLD, CAPE_ICE, CAPE_VOID, CAPE_SUNSET,
    PET_CAT, PET_WOLF, PET_RABBIT, PET_FOX, PET_PIG, PET_SHEEP,
    BALLOON_RED, BALLOON_BLUE, BALLOON_GREEN,
    BALLOON_YELLOW, BALLOON_PURPLE, BALLOON_ORANGE, BALLOON_CYAN, BALLOON_PINK;
}
